module.exports = {
  testEnvironment: "jsdom",
  roots: ["<rootDir>/src"],
  testMatch: ["**/__tests__/**/*.{js,jsx}", "**/*.{test,spec}.{js,jsx}"],
  collectCoverageFrom: [
    "public/javascripts/**/*.js",
    "!public/javascripts/**/*.test.js",
    "!public/javascripts/**/*.spec.js",
    "!public/javascripts/**/node_modules/**",
    "!public/javascripts/user/**",
    "!public/javascripts/tabs/**",
    "!public/javascripts/auth/core/**",
    "!public/javascripts/auth/ui/**",
    "!public/javascripts/rastreamento/events/**",
    "!public/javascripts/rastreamento/renderers/**",
    "!public/javascripts/rastreamento/components/**",
    "!public/javascripts/rastreamento/api/**",
    "!public/javascripts/rastreamento/rastreamento.js",
    "!public/javascripts/dashboard/**",
    "!public/javascripts/core/**",
    "!public/javascripts/login/**",
    "!public/javascripts/admin/**",
    "!public/javascripts/ui/**",
    "!public/javascripts/tools/**",
    "!public/javascripts/utils/scriptLoader.js",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov", "html"],
  setupFilesAfterEnv: ["<rootDir>/src/setupTests.js"],
  testTimeout: 10000,
  verbose: true,
  coveragePathIgnorePatterns: [
    "/node_modules/",
    "/coverage/",
    "/src/__tests__/",
    "/.github/",
  ],
  transform: {
    "^.+\\.js$": "<rootDir>/jest-transformer.js",
  },
};
